image: python

stages:
  - generate
  - publish

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "test-generator"

generate_tests:
  stage: generate
  script:
    - cd 234124/tests/hw1/generators
    - python3 ${command}.py
  parallel:
    matrix:
      - command: [ "verify", "compress", "hash", "format" ]
  artifacts:
    untracked: true

publish_results:
  stage: publish
  dependencies:
    - generate_tests
  script:
    - git config user.email $RUNNER_EMAIL
    - git config user.name "ci-bot"
    - git remote add gitlab_origin https://$RUNNER_USERNAME:$ACCESS_TOKEN@gitlab.com/jamalabo1/technion-utils.git
    - git checkout --orphan temp_tests
    - git rm --cached * -r
    - git add "234124/tests/hw*"
    - git commit -m "push back from pipeline"
    - git subtree split --prefix=234124/tests -b tests
    - git checkout tests
    - git push --force gitlab_origin tests -o ci.skip